spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring_security_practice
    username: root
    password: wlsgh425,.
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
server:
  servlet:
    session:
#      초 단위
#      timeout: 1800
#      분 단위
      timeout: 30m